accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('client_register/', views.Client_register, name='client_register'),
    # path('client_register/', views.Client_register.as_view(), name='client_register'),
    path('update-epicier/<str:pk>/',views.updateepicier,name='update-epicier'),
    path('epicier_register/', views.Epicier_register.as_view(), name='epicier_register'),
    path('client_display/', views.client_display, name='client_display'),
    path('update-client/<str:pk>/',views.updateclient,name='update-client'),
    path('delete-client/<str:pk>/',views.deleteclient,name='delete-client'),
        
    #                   PROFILE                   

    path('Profile_display/<str:username>/', views.Profile_display, name='Profile_display'),
    path('password_update/', views.password_update, name='password_update'),

]

epicerie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('epicerie/', include('project.urls')),
]
urlpatterns+=staticfiles_urlpatterns()

project/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),

    #                    Epicerie                    

    path('epicerie_display/', views.epicerie_display, name='epicerie_display'),
    path('create-epicerie/',views.createepicerie,name='createepicerie'),
    path('update-epicerie/<str:pk>/',views.updateepicerie,name='update-epicerie'),
    path('delete-epicerie/<str:pk>/',views.deleteepicerie,name='delete-epicerie'),

    #                    Credits                    

    path('credits_display/', views.credits_display, name='credits_display'),
    path('create-credits/',views.createcredits,name='createcredits'),
    path('update-credits/<str:pk>/',views.updatecredits,name='update-credits'),
    path('delete-credits/<str:pk>/',views.deletecredits,name='delete-credits'),
    
    #                    Produit                    
    
    path('produits_display/', views.produits_display, name='produits_display'),
    path('create-produits/',views.createproduits,name='createproduits'),
    path('update-produits/<str:pk>/',views.updateproduits,name='update-produits'),
    path('delete-produits/<str:pk>/',views.deleteproduits,name='delete-produits'),
    
    #                    Detail Credit                    

    path('credits_detail_display/<int:pk>/', views.credits_detail_display, name='credits_detail_display'),
    # path('credits_detail_display/<int:pk>/', views.CreditsDetailView.as_view(), name='CreditsDetailView'),
    path('createcredits_detail/<int:pk>/', views.createcredits_detail, name='createcredits_detail'),


    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from project.models import Epicerie
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
# Create your models here.
class User(AbstractUser):
    is_Client = models.BooleanField(default=False)
    is_Epicier = models.BooleanField(default=False)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    def __str__(self):
        return str(self.id)+" - "+self.username
    


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=10)
    adress = models.CharField(max_length=500)
    epicerie=models.ForeignKey(Epicerie, on_delete=models.CASCADE,related_name='epicerie',default='1')
    def __str__(self):
        return str(self.user_id)+" - "+self.user.username

class Epicier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=10)
    adress = models.CharField(max_length=500)

project/models.py
# from django.urls import reverse
from django.db import models
from django.db import transaction
# from accounts.models import Epicier,Client

class Epicerie(models.Model):
    Nom_Epicerie=models.CharField(max_length=255)
    Adresse_Epicerie=models.CharField(max_length=255)
    Tel_Epicerie=models.CharField(max_length=10)
    epicier=models.ForeignKey('accounts.Epicier', on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)+" - "+self.Nom_Epicerie


class Produit(models.Model):
    Description_Produit = models.CharField(max_length=250)
    # image=models.ImageField()
    Prix_Produit = models.FloatField()
    Disponibilité = models.BooleanField()
    epicerie=models.ForeignKey('project.Epicerie', on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)+" - "+self.Description_Produit

class Credit(models.Model):
    Date_d_operation = models.DateField()
    # Nombre_d_articles = models.AutoField()
    Total_Credit = models.FloatField()
    Date_d_echeance = models.DateField()
    Etat = models.BooleanField()
    Avance = models.FloatField()
    client=models.ForeignKey('accounts.Client', on_delete=models.CASCADE)
    epicerie=models.ForeignKey(Epicerie, on_delete=models.CASCADE)



class DetailsCredit(models.Model):
    credit=models.ForeignKey(Credit,on_delete=models.CASCADE)
    produit=models.ForeignKey(Produit,on_delete=models.CASCADE)
    # Description_Produit=models.OneToOneField(Produit,on_delete=models.CASCADE)
    Quantite=models.IntegerField()
    # Prix=models.OneToOneField(Produit,on_delete=models.CASCADE, related_name="Prix")
    Total=models.FloatField()
    def DetailsCredit_total(self):
        return self.Quantite * self.produit.Prix
#, related_name="Description_Produit"

accounts/views.py
from email import message
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views.generic import CreateView
from .models import User ,Client,Epicier,Epicerie
from .forms import ClientSignUpForm,EpicierSignUpForm,ClientForm,EpicierForm,ChangePasswordForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash, authenticate, login


# Create your views here.

# class Client_register(CreateView):
    # model = User  
    # form_class = ClientSignUpForm
    # template_name= 'accounts/client_register.html'

    # def form_valid(self, form_class):
    #     user = form_class.data_save()
    #     login(self.request, user)
    #     return redirect('home')

def register(request):
    return render(request, 'accounts/register.html')

class Epicier_register(CreateView):
    model = User  
    form_class = EpicierSignUpForm
    template_name= 'accounts/epicier_register.html'

    def form_valid(self, form_class):
        user = form_class.data_save()
        login(self.request, user)
        return redirect('home')

def Client_register(request):
        if request.method == 'POST' :
            form=ClientSignUpForm(request.POST,user=request.user)
            if form.is_valid():
                form.data_save()
                messages.success(request, "Registration successful." )
                return redirect('home')
            messages.error(request, "Unsuccessful registration. Invalid information.")
        else:
            form=ClientSignUpForm(user=request.user)
        context={'form':form}
        return render(request,'accounts/client_register.html',context)

def login_user(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('home')
            else:
                messages.error(request,"Invalid username or password")
        else:
            messages.error(request,"Invalid username or password")
    return render(request, 'accounts/login.html',context={'form':AuthenticationForm()})

def logout_user(request):
    logout(request)
    return redirect('home')

def client_display(request):
    if request.user.is_superuser ==1:
        client=Client.objects.filter(user_id__is_Client=True,user_id__is_active=True)
    elif request.user.is_Epicier==1:
        epicier=Epicier.objects.get(user=request.user)
        epicerie=Epicerie.objects.filter(epicier=epicier)
        client=[]
        for element in epicerie:
            for c in Client.objects.filter(user_id__is_Client=True,user_id__is_active=True,epicerie=element):
                client.append(c) 
    else:
        return redirect('home')       
    context={'client':client}
    return render(request, 'accounts/client_display.html',context)

def updateepicier(request,pk):
    epicier=Epicier.objects.get(user_id=pk)
    form=EpicierForm(instance=epicier)
    if request.method=='POST':
        form=EpicierForm(request.POST,instance=epicier)
        if form.is_valid():
            form.save()
        return redirect('home')
    else:
        form = EpicierForm(instance=epicier)
    context={'form':form}
    return render(request,'accounts/epicier_form .html',context)

def updateclient(request,pk):
    client=Client.objects.get(user_id=pk)
    form=ClientForm(instance=client)
    if request.method=='POST':
        form=ClientForm(request.POST,instance=client)
        if form.is_valid():
            # client.save()
            form.save()
            return redirect('home')
    else:
        form = ClientForm(instance=client)
    context={'form':form}
    return render(request,'accounts/client_form.html',context)

def deleteclient(request,pk):
    client=Client.objects.get(user_id=pk)
    if request.method=='POST':
        user=User.objects.get(id=pk)
        user.is_active=False
        user.save()
        client.delete( )
        return redirect('home')
    return render(request,'project/delete.html',{'obj':client})

class Client_create(CreateView):
    model = User  
    form_class = ClientSignUpForm
    template_name= 'accounts/client_form.html'

    def form_valid(self, form_class):
        user = form_class.data_save()
        return redirect('client_display')

"""                   Profile                   """

def Profile_display(request,username):
    user = User.objects.get(username=username)
    context = {'user': user}
    if user.is_Client:
        client = Client.objects.get(user=user)
        context['client'] = client
    elif user.is_Epicier:
        epicier = Epicier.objects.get(user=user)
        context['epicier'] = epicier
    return render(request, 'accounts/profile.html', context)
@login_required
def password_update(request):
    if request.method == 'POST':
        password_form = ChangePasswordForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            auth_user = authenticate(username=user.username, password=password_form.cleaned_data['new_password2'])
            login(request, auth_user)
            messages.success(request, 'Votre profil a été mis à jour.')
            return redirect('home')
    else:
            password_form = ChangePasswordForm(request.user)
    context = {
        'password_form': password_form,
    }
    return render(request, 'accounts/changepassword.html', context)

accounts/templates/accounts/changepassword.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
{% if user.is_authenticated%}
<style>
    body{
     background-size: cover;
     background-image:url("{% static 'assets/img/hallway2.jpg' %}");
     backdrop-filter: blur(10px);
     height: auto;
     }
   .container2{
     color: white;
     margin: 0 auto;
     padding-top: 15px;
    width: 50%;
     background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
   }
   .form-control {
    margin-bottom: 10px;
   }
   .form-group{
    width: 80%;
    margin: 0 auto;

  }
 
   </style>
<div class="container container2">  
  <h1 class="text-center" >Changer le Mot de Passe</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="col-form-label" for="id_old_password">Ancien Mot de passe:</label>
      <input class="form-control" type="password" name="old_password" autocomplete="current-password" autofocus required id="id_old_password">
    </div>  
    <div class="form-group">
      <label class="col-form-label"  for="id_new_password1">Nouveau Mot de passe:</label>
      <input class="form-control" type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1">
    </div>  
    <div class="form-group">
      <label class="col-form-label" for="id_new_password2">Confirmation du Nouveau Mot de passe:</label>
      <input class="form-control" type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2">
    </div>  

      
        
      
    <center><input type="submit" value="Changer le Mot de Passe" class="btn btn-outline-success" style="width:50%" ></center>
  </form>
</div>

  {% endif %}
  {% endblock content %}

accounts/templates/accounts/client_display.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
{% if user.is_authenticated%}
<h2 class="text-center">Mes Clients !</h2>
<table class="table" width="600" border="2">
    <thead class="table-dark">
    <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Username</th>
        <th class="text-center">Prénom</th>
        <th class="text-center">Nom</th>
        <th class="text-center">Téléphone</th>
        <th class="text-center">Addresse</th>
        <th class="text-center">Epicerie</th>
        <th class="text-center">Modifier</th>
        <th class="text-center">Supprimer</th>

    </tr>
    </thead>
    {% for element in client %}
    <tr>        
        <td class="text-center">{{element.user_id}}</td>
        <td class="text-center">{{element.user.username}}</td>
        <td class="text-center">{{element.user.first_name}}</td>
        <td class="text-center">{{element.user.last_name}}</td>
        <td class="text-center">{{element.phone_number}}</td>
        <td class="text-center">{{element.adress}}</td>
        <td class="text-center">{{element.epicerie.Nom_Epicerie}}</td>
        <td class="text-center"><a href="{% url 'update-client' element.user_id %}"><i class="fa-solid fa-user-pen"></i></a></td>
        <td class="text-center"><a href="{% url 'delete-client' element.user_id %}"><i class="fa-solid fa-user-minus"></i></a></td>
    </tr>
    {% endfor %}
    
    
</table>
{% else %}
<center><u><b>you have to login !</b></u></center> 
{% endif %}
{% endblock content %}

accounts/templates/accounts/client_form.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
{% if user.is_authenticated%}
<style>
    body{
     background-size: cover;
     background-image:url("{% static 'assets/img/shoppinggirl.jpg' %}");
     backdrop-filter: blur(10px);
     height: auto;
     }
   .container2{
     color: white;
     margin: 0 auto;
     padding-top: 15px;
    width: 50%;
     background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
   }
   .form-control {
    margin-bottom: 10px;
   }
   .form-group{
    width: 80%;
    margin: 0 auto;

  }
 
   </style>
<div class="container container2">
<h1 class="text-center">User</h1>
<br>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}" class="form-label">Prénom:</label>
          {{ form.first_name }}
        </div>
        <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}" class="form-label">Nom:</label>
          {{ form.last_name }}
        </div>
        <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}" class="form-label">Téléphone:</label>
          {{ form.phone_number }}
        </div>
        <div class="form-group">
          <label for="{{ form.adress.id_for_label }}" class="form-label">Addresse:</label>
          {{ form.adress }}
        </div>
        <div class="form-group">
          <label for="{{ form.epicerie.id_for_label }}" class="form-label">Epicerie:</label>
          {{ form.epicerie }}
        </div>
        <div class="form-group">
          <label for="{{ form.user.id_for_label }}" class="form-label">Client:</label>
          {{ form.user }}
        </div>
                <center><input type="submit" value="Enregistrer" class="btn btn-outline-success" style="width:50%" ></center>
    </form>
</div>
{% else %}
<center><u><b>Tu n'as pas l'accès !</b></u></center> 
{% endif %}
{% endblock content %}

accounts/templates/accounts/client_register.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
<style>
    body{
      background-size: cover;
      background-image:url("{% static 'assets/img/shoppinggirl.jpg' %}");
      backdrop-filter: blur(10px);
      height: auto;
      }
    .container2{
      color: white;
       margin: 0 auto;
       padding-top: 15px;
      width: 70%;
      background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
    }
    .form-group{
      width: 95%;
      margin: 0 auto;
  
    }
  </style>
    <div class="container container2">
    <h2 class="text-center">Formulaire d'enregistrement d'un client</h2>
    <br>
    <form action="{% url 'client_register' %}" method="POST" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="col">
              <div class="form-group">
                <label class="col-form-label" for="id_username">Nom d'utilisateur:</label>
                <input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
              </div>
              <div class="form-group">
                <label class="col-form-label" for="id_password1">Mot de passe:</label>
                <input class="form-control" type="password" name="password1" autocomplete="new-password" required id="id_password1">   
                <span class="helptext"><ul><li>Your password must contain at least 8 characters.</li><li>Your password can’t be entirely numeric.</li></ul></span>
              </div>  
              <div class="form-group">
                <label class="col-form-label" for="id_password2">Confirmation du Mot de passe:</label>
                <input class="form-control" type="password" name="password2" autocomplete="new-password" required id="id_password2">
              </div>
              <div class="form-group">
                <label for="{{ form.epicerie.id_for_label }}" class="form-label" style="margin-top: 5px;">Epicerie:</label>
                {{ form.epicerie }}
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label  class="col-form-label" for="id_first_name" >Prénom:</label>
                <input class="form-control" type="text" name="first_name" required id="id_first_name">
              </div>
              <div class="form-group">
                <label  class="col-form-label" for="id_last_name">Nom:</label>
                <input class="form-control" type="text" name="last_name" required id="id_last_name"> 
              </div>
              <div class="form-group">
                <label  class="col-form-label" for="id_phone_number">Téléphone:</label>
                <input maxlength="10" class="form-control" type="text" name="phone_number" required id="id_phone_number">
              </div>
              <div class="form-group">
                <label  class="col-form-label" for="id_adress">Addresse:</label>
                <input class="form-control" type="text" name="adress" required id="id_adress"> 
              </div>
              
            </div>
          </div>
          <br>
        <center><input type="submit" value="Enregistrer" class="btn btn-outline-success" style="width:50%" ></center>
    </form>
</div>

{% endblock content %}

accounts/templates/accounts/epicier_form .html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
{% if user.is_authenticated%}
{% if perms.project.change_epicerie %}              
<style>
    body{
     background-size: cover;
     background-image:url("{% static 'assets/img/shoppinggirl.jpg' %}");
     backdrop-filter: blur(10px);
     height: auto;
     }
   .container2{
     color: white;
     margin: 0 auto;
     padding-top: 15px;
    width: 50%;
     background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
   }
   .form-control {
    margin-bottom: 10px;
   }
   .form-group{
    width: 80%;
    margin: 0 auto;

  }
 
   </style>
<div class="container container2">
<h1 class="text-center">User</h1>
<br>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}" class="form-label">Prénom:</label>
          {{ form.first_name }}
        </div>
        <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}" class="form-label">Nom:</label>
          {{ form.last_name }}
        </div>
        <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}" class="form-label">Téléphone:</label>
          {{ form.phone_number }}
        </div>
        <div class="form-group">
          <label for="{{ form.adress.id_for_label }}" class="form-label">Addresse:</label>
          {{ form.adress }}
        </div>
        
        <div class="form-group">
          <label for="{{ form.user.id_for_label }}" class="form-label">Client:</label>
          {{ form.user }}
        </div>
                <center><input type="submit" value="Enregistrer" class="btn btn-outline-success" style="width:50%" ></center>
    </form>
</div>
{% else %}
<center><u><b>Tu n'as pas l'accès !</b></u></center> 
{% endif %}
{% endif %}
{% endblock content %}

accounts/templates/accounts/epicier_register.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
<style>
  body{
    background-size: cover;
    background-image:url("{% static 'assets/img/vegetables.jpg' %}");
    backdrop-filter: blur(10px);
    height: auto;
    }
  .container2{
    color: white;
     margin: 0 auto;
     padding-top: 15px;
    width: 70%;
    background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
  }
  .form-group{
    width: 95%;
    margin: 0 auto;

  }
</style>
  <div class="container container2">
    <h2 class="text-center">Formulaire d'inscription de l'Epicier </h2>
    <br>
    <form action="{% url 'epicier_register' %}" method="POST" novalidate>
    {% csrf_token %}
    <div class="row">
      <div class="col">
        <div class="form-group">
          <label class="col-form-label" for="id_username">Nom d'utilisateur:</label>
          <input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
        </div>
        <div class="form-group">
          <label class="col-form-label" for="id_password1">Mot de passe:</label>
          <input class="form-control" type="password" name="password1" autocomplete="new-password" required id="id_password1">   
          <span class="helptext"><ul><li>Your password must contain at least 8 characters.</li><li>Your password can’t be entirely numeric.</li></ul></span>
        </div>  
        <div class="form-group">
          <label class="col-form-label" for="id_password2">Confirmation du Mot de passe:</label>
          <input class="form-control" type="password" name="password2" autocomplete="new-password" required id="id_password2">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label  class="col-form-label" for="id_first_name" >Prénom:</label>
          <input class="form-control" type="text" name="first_name" required id="id_first_name">
        </div>
        <div class="form-group">
          <label  class="col-form-label" for="id_last_name">Nom:</label>
          <input class="form-control" type="text" name="last_name" required id="id_last_name"> 
        </div>
        <div class="form-group">
          <label  class="col-form-label" for="id_phone_number">Téléphone:</label>
          <input maxlength="10" class="form-control" type="text" name="phone_number" required id="id_phone_number">
        </div>
        <div class="form-group">
          <label  class="col-form-label" for="id_adress">Addresse:</label>
          <input class="form-control" type="text" name="adress" required id="id_adress"> 
        </div>
      </div>
    </div>
    <br>
  <center><input type="submit" value="S'inscrire" class="btn btn-outline-success" style="width:50%" ></center>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-pages.html' %}
{% load static %}
<style>
   body{
    background-size: cover;
    background-image:url("{% static 'assets/img/vegetables.jpg' %}");
    backdrop-filter: blur(10px);
    height: auto;
    }
  .container2{
    color: white;
    margin: 0 auto;
    padding-top: 15px;
    width: 50%;
    background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
  }
  .form-group{
    width: 80%;
    margin: 0 auto;

  }
   
  </style>
</div>
<div class="container container2">
    <h2 class="text-center">Login</h2> 
    <form action="{% url 'login_user' %}" method="POST" novalidate>
        {% csrf_token %}
              <div class="form-group">
                <label class="col-form-label" for="id_username">Nom d'utilisateur:</label>
                <input class="form-control" type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
              </div>
              <div class="form-group">
                <label class="col-form-label" for="id_password">Mot de passe:</label>
                <input class="form-control" type="password" name="password" autocomplete="current-password" required id="id_password">
              </div>  
        <br>
        <center><input type="submit" value="Se connecter" class="btn btn-outline-success" style="width:50%" ></center>
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'main.html' %}
{% block content %}
{% include 'navbar-profile.html' %}
{% load static %}
{% if user.is_authenticated%}
<style>
    body{
     background-size: cover;
     background-image:url("{% static 'assets/img/vegetablesdisplay2.jpg' %}");
     backdrop-filter: blur(10px);
     height: auto;
     }
   .container2{
     color: white;
     margin: 0 auto;
     padding-top: 15px;
      width: 50%;
     background: linear-gradient(to bottom, rgba(0, 0, 0, 0.3) 0%, rgba(0, 0, 0, 0.7) 80%, #000 100%);
   }
   .form-control {
    margin-bottom: 10px;
   }
   .form-group{
    width: 80%;
    margin: 0 auto;

  }
 
   </style>
<div class="container container2">
    <div class="row my-3 p-3">
        <h1>{{ user.username }}</h1>
        <p>First Name: {{ user.first_name }}</p>
        <p>Last Name: {{ user.last_name }}</p></h1>
        {% if user.is_Client %}
        <p>Téléphone: {{ client.phone_number }}</p></h1>
        <p>Adresse: {{ client.adress }}</p></h1>
        {% elif user.is_Epicier %}
        <p>Téléphone: {{ epicier.phone_number }}</p></h1>
        <p>Adresse: {{ epicier.adress }}</p></h1>
        {% endif %}

        <a href="{% url 'password_update' %}">Modifier le Mot de Passe </a>
        {% if user.is_Client %}
        <a href="{% url 'update-client' user.id %}"><center><input type="submit" value="Modifier" class="btn btn-outline-success" style="width:50%" ></a>
        {% elif user.is_Epicier %}
          <a href="{% url 'update-epicier' user.id %}"><center><input type="submit" value="Modifier" class="btn btn-outline-success" style="width:50%" ></a>
        {% endif %}
    </div>
</div>
    {% endif %}
    {% endblock content %}

accounts/templates/accounts/register.html
{% extends 'main.html' %}
{% block content %}
{% load static %}

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h1>User Registration</h1>
                </div>
                <div class="card-body">
                  <form>
                    <div class="row">
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'client_register' %}">Je suis un client</a>
                       </div>
                       <div class="col-lg-6">
                        <a type="button" class="btn btn-block" href="{% url 'epicier_register' %}">Je suis un épicier</a>
                       </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock content %}